name: dbt CI Trigger After Approval

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types:
      - submitted

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dbt dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt

    - name: Debug GitHub event payload
      run: echo "${{ toJson(github.event) }}"

    - name: Run dbt Cloud job
      env:
        DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN }}
        DBT_ACCOUNT_ID: ${{ secrets.DBT_ACCOUNT_ID }}
        DBT_JOB_ID: ${{ secrets.DBT_JOB_ID }}
      run: |
        curl -X POST "https://cloud.getdbt.com/api/v2/accounts/$DBT_ACCOUNT_ID/jobs/$DBT_JOB_ID/run/" \
          -H "Authorization: Token $DBT_CLOUD_API_TOKEN"
